<?xml version="1.0" encoding="utf-8"?><Database Name="flashPaperDb" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=&quot;C:\Users\LayersSss\Documents\Visual Studio 2010\Projects\LStudio\LCourse\App_Data\flashPaperDb.mdf&quot;;Integrated Security=True;User Instance=True" SettingsObjectName="LCourseDocsConvertService.Properties.Settings" SettingsPropertyName="flashPaperDbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.request" Member="request">
    <Type Name="request">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="path" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>